// Educational example data — not live odds from any bookmaker
const NRL_GAMES = [
  {
    id: 1,
    homeTeam: { name: "Brisbane Broncos", emoji: "🟡", record: "7W 4L" },
    awayTeam: { name: "Melbourne Storm", emoji: "⚡", record: "9W 2L" },
    time: "Thu 7:50pm",
    venue: "Suncorp Stadium",
    isLive: false,
    h2h: { home: 2.10, away: 1.75 },
    line: { home: { label: "+8.5", odd: 1.90 }, away: { label: "-8.5", odd: 1.90 } },
    ou: { over: { label: "46.5", odd: 1.88 }, under: { label: "46.5", odd: 1.93 } },
    analysis: {
      favourite: "Storm",
      confidenceLevel: "High",
      homeFormLast5: "W W L W L",
      awayFormLast5: "W W W W L",
      keyFactor: "Storm's defence concedes just 16.8 pts/game — expect a low-scoring tight contest.",
      recommendation: "Storm H2H or Under 46.5 offer the most value based on current form.",
      weatherForecast: "Clear, 22°C — good conditions",
      avgMargin: "Storm win by avg 12.4 pts this season",
    }
  },
  {
    id: 2,
    homeTeam: { name: "Sydney Roosters", emoji: "🐓", record: "8W 3L" },
    awayTeam: { name: "North QLD Cowboys", emoji: "🤠", record: "5W 6L" },
    time: "Fri 6:00pm",
    venue: "Allianz Stadium",
    isLive: false,
    h2h: { home: 1.55, away: 2.55 },
    line: { home: { label: "-9.5", odd: 1.90 }, away: { label: "+9.5", odd: 1.90 } },
    ou: { over: { label: "48.5", odd: 1.90 }, under: { label: "48.5", odd: 1.90 } },
    analysis: {
      favourite: "Roosters",
      confidenceLevel: "Medium",
      homeFormLast5: "W W W L W",
      awayFormLast5: "L W L L W",
      keyFactor: "Roosters are 6–0 at home this season; Cowboys have lost 4 of last 5 away games.",
      recommendation: "Roosters H2H at $1.55 is reasonable — or try Roosters –9.5 line for better value.",
      weatherForecast: "Partly cloudy, 19°C",
      avgMargin: "Roosters win home games by avg 14.2 pts",
    }
  },
  {
    id: 3,
    homeTeam: { name: "South Sydney Rabbitohs", emoji: "🐰", record: "6W 5L" },
    awayTeam: { name: "Parramatta Eels", emoji: "🐍", record: "4W 7L" },
    time: "Fri 7:55pm",
    venue: "Accor Stadium",
    isLive: true,
    h2h: { home: 1.70, away: 2.20 },
    line: { home: { label: "-5.5", odd: 1.90 }, away: { label: "+5.5", odd: 1.90 } },
    ou: { over: { label: "44.5", odd: 1.85 }, under: { label: "44.5", odd: 1.95 } },
    analysis: {
      favourite: "Rabbitohs",
      confidenceLevel: "Medium",
      homeFormLast5: "W L W W L",
      awayFormLast5: "L L L W L",
      keyFactor: "Eels have conceded 30+ points in 3 of their last 5 away games. Rabbitohs' attack averages 26 pts/game at home.",
      recommendation: "Rabbitohs H2H looks solid at $1.70 — Over 44.5 also attractive given both sides' leaky defences.",
      weatherForecast: "Light rain possible — may keep score lower",
      avgMargin: "Rabbitohs win by 8–12 pts in similar matchups",
    }
  },
  {
    id: 4,
    homeTeam: { name: "Penrith Panthers", emoji: "🐾", record: "10W 1L" },
    awayTeam: { name: "Cronulla Sharks", emoji: "🦈", record: "6W 5L" },
    time: "Sat 3:00pm",
    venue: "BlueBet Stadium",
    isLive: false,
    h2h: { home: 1.40, away: 3.00 },
    line: { home: { label: "-11.5", odd: 1.90 }, away: { label: "+11.5", odd: 1.90 } },
    ou: { over: { label: "50.5", odd: 1.92 }, under: { label: "50.5", odd: 1.88 } },
    analysis: {
      favourite: "Panthers",
      confidenceLevel: "Very High",
      homeFormLast5: "W W W W W",
      awayFormLast5: "L W W L W",
      keyFactor: "Panthers are the form team of the competition — 10 wins from 11 with an average margin of 17.8 pts.",
      recommendation: "Panthers H2H at $1.40 is short — Panthers –11.5 line at $1.90 offers far better value if you're confident.",
      weatherForecast: "Fine, 24°C — perfect conditions",
      avgMargin: "Panthers win home games by avg 18 pts this season",
    }
  },
  {
    id: 5,
    homeTeam: { name: "Melbourne Storm", emoji: "⚡", record: "9W 2L" },
    awayTeam: { name: "NZ Warriors", emoji: "⚔️", record: "5W 6L" },
    time: "Sat 5:30pm",
    venue: "AAMI Park",
    isLive: false,
    h2h: { home: 1.50, away: 2.70 },
    line: { home: { label: "-10.5", odd: 1.90 }, away: { label: "+10.5", odd: 1.90 } },
    ou: { over: { label: "42.5", odd: 1.90 }, under: { label: "42.5", odd: 1.90 } },
    analysis: {
      favourite: "Storm",
      confidenceLevel: "High",
      homeFormLast5: "W W W L W",
      awayFormLast5: "L L W L W",
      keyFactor: "Storm's defence is elite at AAMI Park — Under 42.5 is historically profitable in Storm home games.",
      recommendation: "Storm H2H or Under 42.5 — Storm hold opponents to under 22 pts in 7 of 9 home games.",
      weatherForecast: "Overcast, 16°C — Melbourne winter conditions",
      avgMargin: "Storm win at AAMI Park by avg 15 pts",
    }
  },
  {
    id: 6,
    homeTeam: { name: "Canberra Raiders", emoji: "🟢", record: "5W 6L" },
    awayTeam: { name: "Gold Coast Titans", emoji: "🌟", record: "3W 8L" },
    time: "Sun 4:05pm",
    venue: "GIO Stadium",
    isLive: false,
    h2h: { home: 1.65, away: 2.30 },
    line: { home: { label: "-6.5", odd: 1.90 }, away: { label: "+6.5", odd: 1.90 } },
    ou: { over: { label: "46.5", odd: 1.88 }, under: { label: "46.5", odd: 1.92 } },
    analysis: {
      favourite: "Raiders",
      confidenceLevel: "Low-Medium",
      homeFormLast5: "L W L W W",
      awayFormLast5: "L L L W L",
      keyFactor: "Raiders are inconsistent at home — Titans have actually won 2 of last 3 away games vs similarly ranked sides.",
      recommendation: "Raiders H2H at $1.65 is okay, but Raiders are prone to upsets. Titans +6.5 line offers strong underdog value.",
      weatherForecast: "Cold, 10°C — could suit the heavier Raiders pack",
      avgMargin: "These sides split evenly; last 4 meetings decided by <10 pts",
    }
  }
];

const SCENARIOS = [
  { stake: 10, label: "Short fav ($1.40)", odds: 1.40 },
  { stake: 10, label: "Even match ($1.90)", odds: 1.90 },
  { stake: 10, label: "Underdog ($2.80)", odds: 2.80 },
  { stake: 10, label: "Punt ($6.00)", odds: 6.00 },
  { stake: 10, label: "First try scorer ($8.00)", odds: 8.00 },
];
